"""Recipe 02 -- Async rollout / AgentLoop  (strictly on-policy)
==============================================================

verl reference
--------------
    actor_rollout_ref.rollout.mode=async
    verl/experimental/agent_loop/{agent_loop.py, agent_loop_manager}
      AgentLoopManager  -> AgentLoopWorker -> AsyncLLMServerManager -> AsyncLLMServer
    verl docs: advance/agent_loop

What verl actually does
-----------------------
Synchronous rollout is one blocking `generate_sequences(batch)` call: the batch
goes into the engine, the batch comes out, and the phase ends when the *longest*
sequence finishes. Async rollout replaces that with one coroutine per trajectory
against a live vLLM/SGLang server:

  * `AgentLoopWorker` schedules many `AgentLoopBase` coroutines concurrently --
    at the limit, one per prompt.
  * `AsyncLLMServerManager` proxies them across server replicas, routing each new
    request to the replica with the fewest in-flight requests, and pinning
    subsequent turns of the same `request_id` to that replica (sticky session,
    so the multi-turn KV cache stays put).
  * The engine does continuous batching underneath, so a finished sequence's slot
    is refilled immediately instead of the whole batch waiting on its tail.
  * `AgentLoopManager` wake_up()s the servers to sync weights before generation
    and sleep()s them afterwards to release the KV cache back to the trainer.

Crucially this changes *nothing* about policy freshness. The barrier between
generation and training is still there. Every rollout in batch N is generated by
policy version N. This is the last stop before you start paying in staleness.

How that maps onto this simulator
---------------------------------
Two mechanisms port over, one honest caveat.

  1. Least-loaded routing replaces the baseline's static `gpus[i % len(gpus)]`.
     Round-robin pins a rollout to a GPU at submit time, so a GPU that draws a
     slow tail of work finishes late while its neighbour idles. Routing at
     *dispatch* time instead lets work migrate.

  2. Tail overlap. Once all of a batch's rollouts have been dispatched, GPU
     occupancy is decaying no matter what -- there is nothing left to admit.
     A GPU whose in-flight set hits zero is therefore free to flip to backward
     *at zero cost*, while its neighbours are still finishing stragglers. This is
     the sleep()/wake_up() flip, and at the batch tail it is genuinely free.

  Caveat, stated up front: at the default config (batch_size=256 == num_gpus *
  slots_per_gpu == 4*64) mechanism 1 has almost nothing to do. Every GPU gets
  exactly 64 rollouts, every slot is occupied from t=0, and no work can migrate
  because no slot ever frees while work is queued. Routing wins only when the
  batch oversubscribes the slots. Run this file directly to see both regimes.

The real result of this recipe is a negative one, and it is the most important
number in the whole set: strictly on-policy has a hard floor at roughly
max(latency) + backward per batch. Every large win in async RL is bought with
staleness. Recipes 03 and 04 buy it.
"""

from __future__ import annotations

import asyncio
from collections import deque
from dataclasses import dataclass

from grpo import GPU, GradientOptimizer, Rollout
from recipe_common import Metrics, Signal, chunked


@dataclass
class AgentLoopConfig:
    overlap_tail: bool = True
    """Flip a GPU to backward as soon as its in-flight generation drains, rather
    than waiting for the whole batch. Only ever engages after every rollout has
    been dispatched, so it never costs admission."""

    engine_switch_ms: float = 0.0
    """Simulated vLLM sleep()/wake_up() cost per role flip. The assignment's cost
    model has no such term; non-zero values show how quickly tail overlap stops
    paying for itself."""


class AsyncLLMServerManager:
    """Routes generation requests across GPUs the way verl routes across replicas.

    Load is tracked at dispatch time, not submit time. `_pick` and the load
    increment are separated by no `await`, so they are atomic with respect to the
    event loop -- two coroutines can never both see the same GPU as least-loaded
    and oversubscribe it.
    """

    def __init__(self, gpus: list[GPU], slots_per_gpu: int) -> None:
        self._gpus = gpus
        self._slots = slots_per_gpu
        self._load = [0] * len(gpus)
        self._awake = [True] * len(gpus)
        self._free = Signal()
        self.routed = [0] * len(gpus)

    def sleep(self, gpu_id: int) -> None:
        """Stop routing to this replica; it is about to take the trainer's role."""
        self._awake[gpu_id] = False

    def wake_up(self, gpu_id: int) -> None:
        self._awake[gpu_id] = True
        self._free.notify()

    def load(self, gpu_id: int) -> int:
        return self._load[gpu_id]

    def _pick(self) -> int | None:
        best, best_load = None, self._slots
        for i, load in enumerate(self._load):
            if self._awake[i] and load < best_load:
                best, best_load = i, load
        return best

    async def generate(self, rollout: Rollout, on_admit=None) -> None:
        while True:
            i = self._pick()
            if i is not None:
                break
            await self._free.wait()

        self._load[i] += 1
        self.routed[i] += 1
        if on_admit is not None:
            on_admit()
        try:
            await self._gpus[i].run_inference(rollout)
        finally:
            self._load[i] -= 1
            self._free.notify()

class _BatchRun:
    """Tracks one batch through generation and backward.

    Chunk membership is fixed **up front, by rollout index** -- identical to the
    baseline's partitioning -- and a chunk becomes claimable the moment its own
    members have all finished generating.

    That detail is not cosmetic, and getting it wrong cost 15% here. The obvious
    design is to pour finished rollouts into a shared FIFO and cut chunks off the
    front. But every rollout in a batch starts at the same instant, so completion
    order *is* latency order: the first chunk ends up holding the 64 fastest
    rollouts and the last chunk the 64 slowest. `backward_latency_for` prices a
    chunk at its median, and the phase costs the max over chunks running in
    parallel -- so latency-sorted chunks turn a ~215ms backward phase into a
    ~550ms one. Measured at 0.85x vs baseline before the fix.

    Note the same cost model rewards the inverse abuse: a chunk of "33 tiny + 31
    huge" prices as tiny, so chunk composition can be gamed toward the floor.
    Index-order membership is the neutral choice -- it neither correlates with
    latency nor anti-correlates with it, which is exactly what the baseline does.
    """

    def __init__(self, batch: list[Rollout], slots: int, metrics: Metrics) -> None:
        self.queued = len(batch)
        self.backwarded = 0
        self.total = len(batch)
        self.metrics = metrics
        self.changed = Signal()

        self.chunks = chunked(batch, slots)
        self._outstanding = [len(c) for c in self.chunks]
        self._owner = {}
        for ci, chunk in enumerate(self.chunks):
            for r in chunk:
                self._owner[id(r)] = ci
        self.ready_chunks: deque[int] = deque()

    @property
    def all_dispatched(self) -> bool:
        return self.queued == 0

    def on_admit(self) -> None:
        self.queued -= 1
        if self.queued == 0:
            self.changed.notify()

    def retire(self, rollout: Rollout) -> None:
        ci = self._owner[id(rollout)]
        self._outstanding[ci] -= 1
        if self._outstanding[ci] == 0:
            self.ready_chunks.append(ci)
            self.metrics.peak_queue_depth = max(self.metrics.peak_queue_depth, len(self.ready_chunks))
        self.changed.notify()

    def claim(self) -> list[Rollout] | None:
        if self.ready_chunks:
            return self.chunks[self.ready_chunks.popleft()]
        return None


async def _generate_one(mgr: AsyncLLMServerManager, rollout: Rollout, run: _BatchRun) -> None:
    await mgr.generate(rollout, on_admit=run.on_admit)
    run.retire(rollout)


async def _backward_worker(
    gpu: GPU,
    mgr: AsyncLLMServerManager,
    run: _BatchRun,
    cfg: AgentLoopConfig,
) -> None:
    """Wait for this GPU to drain, then serve backward chunks for the rest of the batch.

    One worker per GPU, and only one: `GPU.run_backward` acquires its permits one
    at a time, so two concurrent backwards on the same GPU can each hold a partial
    set and deadlock. Serialising per GPU is not an optimisation, it is a
    correctness requirement.
    """
    while not run.all_dispatched:
        await run.changed.wait()

    mgr.sleep(gpu.id)
    run.metrics.role_switches += 1
    try:
        while mgr.load(gpu.id) > 0:
            await run.changed.wait()

        if cfg.engine_switch_ms:
            await asyncio.sleep(gpu.cfg.sim(cfg.engine_switch_ms))

        while run.backwarded < run.total:
            chunk = run.claim()
            if chunk is None:
                await run.changed.wait()
                continue
            await gpu.run_backward(chunk)
            run.metrics.backward_calls += 1
            run.backwarded += len(chunk)
            run.changed.notify()

        if cfg.engine_switch_ms:
            await asyncio.sleep(gpu.cfg.sim(cfg.engine_switch_ms))
    finally:
        mgr.wake_up(gpu.id)


async def _run_batch(
    batch: list[Rollout],
    gpus: list[GPU],
    mgr: AsyncLLMServerManager,
    slots: int,
    cfg: AgentLoopConfig,
    metrics: Metrics,
) -> None:
    run = _BatchRun(batch, slots, metrics)

    gen = [asyncio.create_task(_generate_one(mgr, r, run)) for r in batch]

    if cfg.overlap_tail:
        bwd = [asyncio.create_task(_backward_worker(g, mgr, run, cfg)) for g in gpus]
        await asyncio.gather(*gen)
        run.changed.notify()
        await asyncio.gather(*bwd)
    else:
        # Hard phase barrier: agent-loop generation, then a work-stealing backward.
        await asyncio.gather(*gen)
        queue = deque(run.chunks)

        async def serve(gpu: GPU) -> None:
            while queue:
                chunk = queue.popleft()
                await gpu.run_backward(chunk)
                metrics.backward_calls += 1

        await asyncio.gather(*[serve(g) for g in gpus])
        run.backwarded = run.total


METRICS = Metrics(name="train_agent_loop")
CONFIG = AgentLoopConfig()


async def train_agent_loop(
    rollouts: list[Rollout],
    gpus: list[GPU],
    batch_size: int,
    slots_per_gpu: int,
    optimizer: GradientOptimizer,
) -> None:
    """Strictly on-policy training with async (continuous-batching) rollout."""
    global METRICS
    METRICS = Metrics(name="train_agent_loop")
    METRICS.extra["overlap_tail"] = CONFIG.overlap_tail

    mgr = AsyncLLMServerManager(gpus, slots_per_gpu)

    for start in range(0, len(rollouts), batch_size):
        batch = rollouts[start : start + batch_size]
        await _run_batch(batch, gpus, mgr, slots_per_gpu, CONFIG, METRICS)
        # Zero staleness: every rollout in this batch captured the same version,
        # which is exactly the current one, so the increment always lands.
        await optimizer.optimizer_step(batch)

    METRICS.extra["routed"] = "/".join(str(n) for n in mgr.routed)


if __name__ == "__main__":
    from grpo import Config, ModelState, make_rollouts, run_and_report, train_baseline

    async def sweep(cfg: Config, label: str) -> None:
        print(f"\n{'=' * 52}\n  {label}\n  batch={cfg.batch_size}  slots_total={cfg.num_gpus * cfg.slots_per_gpu}")
        rollouts = make_rollouts(cfg)
        model_state = ModelState()
        gpus = [GPU(id=i, cfg=cfg, model_state=model_state) for i in range(cfg.num_gpus)]
        optimizer = GradientOptimizer(batch_size=cfg.batch_size, model_state=model_state)

        base = await run_and_report("train_baseline", train_baseline, rollouts, gpus, optimizer, cfg)
        for overlap in (False, True):
            CONFIG.overlap_tail = overlap
            got = await run_and_report(
                f"agent_loop (overlap_tail={overlap})", train_agent_loop, rollouts, gpus, optimizer, cfg
            )
            print(f"  Metrics    : {METRICS.line()}")
            if base and got:
                print(f"  Speedup    : {base / got:.2f}x")

    async def main() -> None:
        await sweep(Config(), "saturated: batch == total slots")
        await sweep(Config(batch_size=1024, num_batches=12), "oversubscribed: batch == 4x total slots")

    asyncio.run(main())
